[package]
description = "Procedural macro for osmosis-std"
edition = "2021"
license = "MIT OR Apache-2.0"
name = "rs-bitsong-derive"
version = "0.0.1"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]

[lib]
proc-macro = true

[dependencies]
itertools = "0.10.3"
proc-macro2 = "1.0.40"
prost-types = "0.14.1"
quote = "1.0.20"
syn = "1.0.98"

[dev-dependencies]
cosmwasm-std = { version = "3.0.1", features = ["stargate"] }
prost = "0.14.1"
serde = "1.0.142"
trybuild = { version = "1.0.63", features = ["diff"] }
