[package]
name = "rust-proto-gen"
version = "0.1.0"
authors = [ ""]
edition = "2018"
publish = false
rust-version = "1.75"

[dependencies]
prost = "0.14.1"
tonic = "0.14.1" 
tonic-prost-build = "0.14.1"
regex = "1"
walkdir = "2"
