[package]
name = "rust-proto-gen"
version = "0.1.0"
authors = [ ""]
edition = "2018"
publish = false
rust-version = "1.75"

[dependencies]
prost = "0.13"
prost-build = "0.13"
tonic = { version = "0.13", features = ["transport"] }
tonic-build = "0.13"
regex = "1"
walkdir = "2"